services:
  study-buddies:
    build:
      context: .
      # Correct the path to your Dockerfile
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - ENV=DEV
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - .:/app
      - /app/tmp
    depends_on:
      - study-buddies-postgres # Ensure DB starts first
      - study-buddies-redis
    networks:
      - study-buddies-net

  # PostgreSQL Service
  study-buddies-postgres:
    container_name: study-buddies-postgres
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=studybuddies
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=study_buddies
    volumes:
      - study-buddies-postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - study-buddies-net
  
  # Redis Service
  study-buddies-redis:
    container_name: study-buddies-redis
    image: redis:7-alpine
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - study-buddies-redis:/data
    networks:
      - study-buddies-net

volumes:
  study-buddies-postgres:
    external: false
  study-buddies-redis:
    external: false

networks:
  study-buddies-net:
    name: study-buddies-net
