services:
  study-buddies:
    build:
      context: .
      # Correct the path to your Dockerfile
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - ENV=DEV
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - .:/app
      - /app/tmp
    depends_on:
      - study-buddies-postgres # Ensure DB starts first
      - study-buddies-redis
      - study-buddies-rabbitmq
      - study-buddies-kafka

    networks:
      - study-buddies-net

  # PostgreSQL Service
  study-buddies-postgres:
    container_name: study-buddies-postgres
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=studybuddies
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=study_buddies
    volumes:
      - study-buddies-postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - study-buddies-net

  # Redis Service
  study-buddies-redis:
    container_name: study-buddies-redis
    image: redis:7-alpine
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - '6379:6379'
    volumes:
      - study-buddies-redis:/data
    networks:
      - study-buddies-net

  # Elasticsearch Service
  study-buddies-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: study-buddies-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Nonaktifkan security (untuk dev mode)
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # Sesuaikan dengan RAM server
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - study-buddies-elasticsearch:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    networks:
      - study-buddies-net

  # Kibana Service (Optional)
  study-buddies-kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: study-buddies-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://study-buddies-elasticsearch:9200
    ports:
      - '5601:5601'
    networks:
      - study-buddies-net
    depends_on:
      - study-buddies-elasticsearch

    # RabbitMQ Service
  study-buddies-rabbitmq:
    image: rabbitmq:3-management
    container_name: study-buddies-rabbitmq
    ports:
      - '5672:5672'     # AMQP
      - '15672:15672'   # RabbitMQ Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - study-buddies-rabbitmq:/var/lib/rabbitmq
    networks:
      - study-buddies-net

  # KAFKA with ZOOKEEPER Service
  study-buddies-zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: study-buddies-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - study-buddies-net

  study-buddies-kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: study-buddies-kafka
    depends_on:
      - study-buddies-zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: study-buddies-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://study-buddies-kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # ⬅️ ini penting!
    volumes:
      - study-buddies-kafka:/var/lib/kafka/data
    networks:
      - study-buddies-net

  study-buddies-kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: study-buddies-kafka-ui
    ports:
      - "8081:8080"  # UI akan bisa diakses di localhost:8081
    depends_on:
      - study-buddies-kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=StudyBuddiesKafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=study-buddies-kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=study-buddies-zookeeper:2181
    networks:
      - study-buddies-net


volumes:
  study-buddies-postgres:
    external: false
  study-buddies-redis:
    external: false
  study-buddies-elasticsearch:
    external: false
  study-buddies-rabbitmq:
    external: false
  study-buddies-kafka:
    external: false


networks:
  study-buddies-net:
    name: study-buddies-net
